<a href="https://colab.research.google.com/github/a-forty-two/ADLJanApr/blob/main/conv1D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Convolution Layer
# ML is anyway Dense-Dense-> weights and biases are generated 
# finer patterns -> treat those patterns as inputs, rather than inputs as-it-is

In [1]:
from keras.models import Sequential
from keras.layers import Dense, Conv1D, Flatten, MaxPooling1D
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.datasets import load_iris
from numpy import unique


In [2]:

iris = load_iris()
X, y = iris.data, iris.target
print(X.shape)

x = X.reshape(X.shape[0], X.shape[1], 1)
print(x.shape)

(150, 4)
(150, 4, 1)


In [ ]:
print(X[0]) # petal iris

[5.1 3.5 1.4 0.2]


In [ ]:
y[:-5]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [3]:

xtrain, xtest, ytrain, ytest=train_test_split(x, y, test_size=0.15)


In [4]:
from tensorflow import keras
import tensorflow as tf
model = keras.models.Sequential()

In [5]:
model.add(Conv1D(4, 2, activation = tf.nn.relu,input_shape=(4,1)))

In [6]:
# compress the image
model.add(MaxPooling1D())

In [7]:
import tensorflow as tf
model.add(Dense(3, activation = tf.nn.softmax))

In [8]:
model.compile(loss = 'sparse_categorical_crossentropy', 
     optimizer = "adam",               
              metrics = ['accuracy'])

model.fit(xtrain, ytrain, batch_size=16,epochs=1, verbose=0)
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d (Conv1D)             (None, 3, 4)              12        
                                                                 
 max_pooling1d (MaxPooling1D  (None, 1, 4)             0         
 )                                                               
                                                                 
 dense (Dense)               (None, 1, 3)              15        
                                                                 
Total params: 27
Trainable params: 27
Non-trainable params: 0
_________________________________________________________________


In [9]:
model.layers[0].get_weights()

[array([[[-0.22013557,  0.606614  , -0.12793107, -0.25314915]],
 
        [[ 0.1852968 ,  0.07635991,  0.7738242 , -0.45516777]]],
       dtype=float32),
 array([-0.00778324, -0.00765508,  0.00176376,  0.        ], dtype=float32)]

In [10]:
pred = model.predict(xtest)
pred_y = pred.argmax(axis=-1)

In [11]:
pred_y[5:15]

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])