<a href="https://colab.research.google.com/github/a-forty-two/ADLJanApr/blob/main/TF2Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.7.0


In [2]:
x = tf.constant(3)
x
# A Pointer to a Scalar tensor 

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [5]:
x = tf.constant([3, 5, 7]) 
x
# A Pointer to a Vector tensor 

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 5, 7], dtype=int32)>

In [8]:
x = tf.constant([[3, 5, 7],
 [4, 6, 8]])
x
# Matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 5, 7],
       [4, 6, 8]], dtype=int32)>

In [9]:
#BEYOND 3-D
# create a basic shape and start stacking
x1 = tf.constant([2, 3, 4])
x2 = tf.stack([x1, x1])
x3 = tf.stack([x2, x2, x2, x2])
x4 = tf.stack([x3, x3])

In [10]:
x1

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

In [11]:
x2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [2, 3, 4]], dtype=int32)>

In [12]:
x3

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[2, 3, 4],
        [2, 3, 4]],

       [[2, 3, 4],
        [2, 3, 4]],

       [[2, 3, 4],
        [2, 3, 4]],

       [[2, 3, 4],
        [2, 3, 4]]], dtype=int32)>

In [13]:
x4

<tf.Tensor: shape=(2, 4, 2, 3), dtype=int32, numpy=
array([[[[2, 3, 4],
         [2, 3, 4]],

        [[2, 3, 4],
         [2, 3, 4]],

        [[2, 3, 4],
         [2, 3, 4]],

        [[2, 3, 4],
         [2, 3, 4]]],


       [[[2, 3, 4],
         [2, 3, 4]],

        [[2, 3, 4],
         [2, 3, 4]],

        [[2, 3, 4],
         [2, 3, 4]],

        [[2, 3, 4],
         [2, 3, 4]]]], dtype=int32)>

In [ ]:
#Matrix reshpae-> the total tensor count CANNOT change!
# if before shape was -> 1 X 2 X 4 = total elements= 8
# possible-> 1X8, 8X1, 2X4, 4X2, 1 X 4 X 2, 2X2X2, 1X1X2X2X2
# impossible-> 3X3 , 1,16

In [19]:
# possible
x = tf.constant([
 [3, 5, 7],
 [4, 6, 8]
])
y = tf.reshape(x, [3,2,1])
y

<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[3],
        [5]],

       [[7],
        [4]],

       [[6],
        [8]]], dtype=int32)>

In [16]:
#impossible (Error expected)
x = tf.constant([
 [3, 5, 7],
 [4, 6, 8]
])
y = tf.reshape(x, [2, 4])
y

InvalidArgumentError: ignored

In [3]:
def abc():
  return 0
# everything is POINTER MANIPULATION!

In [4]:
abc

<function __main__.abc>