<a href="https://colab.research.google.com/github/a-forty-two/ADLJanApr/blob/main/TF2Basics_reading_data_into_datasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.7.0


In [2]:
x = tf.constant(3)
x
# A Pointer to a Scalar tensor 

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [5]:
x = tf.constant([3, 5, 7]) 
x
# A Pointer to a Vector tensor 

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 5, 7], dtype=int32)>

In [8]:
x = tf.constant([[3, 5, 7],
 [4, 6, 8]])
x
# Matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 5, 7],
       [4, 6, 8]], dtype=int32)>

In [9]:
#BEYOND 3-D
# create a basic shape and start stacking
x1 = tf.constant([2, 3, 4])
x2 = tf.stack([x1, x1])
x3 = tf.stack([x2, x2, x2, x2])
x4 = tf.stack([x3, x3])

In [10]:
x1

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

In [11]:
x2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [2, 3, 4]], dtype=int32)>

In [12]:
x3

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[2, 3, 4],
        [2, 3, 4]],

       [[2, 3, 4],
        [2, 3, 4]],

       [[2, 3, 4],
        [2, 3, 4]],

       [[2, 3, 4],
        [2, 3, 4]]], dtype=int32)>

In [13]:
x4

<tf.Tensor: shape=(2, 4, 2, 3), dtype=int32, numpy=
array([[[[2, 3, 4],
         [2, 3, 4]],

        [[2, 3, 4],
         [2, 3, 4]],

        [[2, 3, 4],
         [2, 3, 4]],

        [[2, 3, 4],
         [2, 3, 4]]],


       [[[2, 3, 4],
         [2, 3, 4]],

        [[2, 3, 4],
         [2, 3, 4]],

        [[2, 3, 4],
         [2, 3, 4]],

        [[2, 3, 4],
         [2, 3, 4]]]], dtype=int32)>

In [ ]:
#Matrix reshpae-> the total tensor count CANNOT change!
# if before shape was -> 1 X 2 X 4 = total elements= 8
# possible-> 1X8, 8X1, 2X4, 4X2, 1 X 4 X 2, 2X2X2, 1X1X2X2X2
# impossible-> 3X3 , 1,16

In [19]:
# possible
x = tf.constant([
 [3, 5, 7],
 [4, 6, 8]
])
y = tf.reshape(x, [3,2,1])
y

<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[3],
        [5]],

       [[7],
        [4]],

       [[6],
        [8]]], dtype=int32)>

In [16]:
#impossible (Error expected)
x = tf.constant([
 [3, 5, 7],
 [4, 6, 8]
])
y = tf.reshape(x, [2, 4])
y

InvalidArgumentError: ignored

In [20]:
# x <- 2
x = tf.Variable(2.0, dtype=tf.float32, name='my_variable')
# x <- 48.5
x.assign(45.8)
# x <- x + 4
x.assign_add(4)
# x <- x - 3
x.assign_sub(3)
x

<tf.Variable 'my_variable:0' shape=() dtype=float32, numpy=46.8>

In [21]:
# in y=mx+c, this represents mx
w = tf.Variable([[1.], [2.]]) # weight (or m in mx+c) is a variable
x = tf.constant([[3., 4.]]) # x represents a record, an observation, a row of tabular data
tf.matmul(w, x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 4.],
       [6., 8.]], dtype=float32)>

In [22]:
# order matters-> xm is not same as mx
tf.matmul(x, w)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[11.]], dtype=float32)>

In [23]:
def create_dataset(X, Y, epochs, batch_size):
 dataset = tf.data.Dataset.from_tensor_slices((X, Y))
 dataset = dataset.repeat(epochs).batch(batch_size, drop_remainder=True)
 return dataset

In [25]:
x = [10, 20, 30, 40, 50, 60]
y = [1,2,3,4,5,6]
z = create_dataset(x,y, 2, 2)

In [26]:
z

<BatchDataset shapes: ((2,), (2,)), types: (tf.int32, tf.int32)>

In [27]:
#IN MEMORY (on RAM data)
t = tf.constant([[4, 2], [5, 3]])
ds = tf.data.Dataset.from_tensors(t) # [[4, 2], [5, 3]]
ds

<TensorDataset shapes: (2, 2), types: tf.int32>

In [28]:
t = tf.constant([[4, 2], [5, 3]])
ds = tf.data.Dataset.from_tensor_slices(t) 
ds

<TensorSliceDataset shapes: (2,), types: tf.int32>

In [3]:
def abc():
  return 0
# everything is POINTER MANIPULATION!

In [4]:
abc

<function __main__.abc>

In [42]:
def parse_row(records):
 cols = tf.io.decode_csv(records, record_defaults=[[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0]])
 features = {'radius_mean': cols[2]}
 label = cols[1]
 return features, label

def create_dataset():
 csv_file_path = '/content/breastcancer_data.csv'
 dataset = tf.data.TextLineDataset(csv_file_path)
 dataset = dataset.map(parse_row)
 dataset = dataset.shuffle(42).repeat(15).batch(128)
 return dataset

In [43]:
create_dataset()

<BatchDataset shapes: ({radius_mean: (None,)}, (None,)), types: ({radius_mean: tf.int32}, tf.int32)>